### ISSUE TITLE
Regression in the Attachments portlet -- Cannot find template script at ID 'qq-template'!

### ISSUE THREAD

**Issue by drewwills** [Jasig/SimpleContentPortlet#42]
Recently the FineUploader component was upgraded from 3.3.0 to 5.13.0, but `attachments/main.jsp` page was not updated to reflect changes in the API.

https://github.com/Jasig/SimpleContentPortlet/commit/ceaefb0d6a1227d9385bd79b6aa0dcbc10c146cd#diff-0143c4f4ba6b0c02df994db35a68e8cb

**Comment by drewwills** [comment]
@ChristianMurphy & @bjagg -- I believe we fixed this one... didn't we?

**Comment by ChristianMurphy** [comment]
I believe https://github.com/Jasig/SimpleContentPortlet/pull/43 resolved this

**Comment by drewwills** [comment]
Fixed by #43
